### ISSUE TITLE
Refactor with hooks

### ISSUE THREAD

**Issue by chepkok3** [chepkok3/Math-Magicians#4]
- [x] There is no need for me to refactor with hooks because that has already been done in the last PR. 
- [x] Check the hooks  [here](https://github.com/chepkok3/Math-Magicians/blob/5ebb265c9863737971225f558b76c11dbf18c0db/src/components/Calculator.js#L1-L14)
- [x] The Calculator component has been defined as a function that returns JSX, which is the UI that is rendered to the screen.
- [x] The useState hook is used within the Calculator component. I have used the hook to allow the component to manage state without requiring the use of class components.

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Stanley,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
💠 Hooks implemented correctly!

Cheers..Happy coding! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
